### ISSUE TITLE
Not enough full stack developer

### ISSUE THREAD

**Issue by hugomd** [jammatpic/simple-calculator#1]

**Comment by jammatpic** [comment]
I think I'll close this issue by the end of the year.

**Comment by hugomd** [comment]
Can this be closed yet?

**Comment by jammatpic** [comment]
I'll get around to it this summer :)

**Comment by jammatpic** [comment]
I got offered a web dev job, so I guess I can finally close this.

**Comment by hugomd** [comment]
Oooh, where are you working?
